### ISSUE TITLE
Static HTML links in README.rst are broken (HTTP 404)

### ISSUE THREAD

**Issue by Sonophoto** [xesscorp/pygmyhdl#2]
Here is the text I got from the server after clicking the HTML1 static page link.

Not Found

The requested URL /static/media/pages/pygmyhdl/examples/1_blinker/fastest_easiest_FPGA_blinker_ever.html was not found on this server.
Apache/2.2.22 (Ubuntu) Server at www.xess.com Port 80

**Comment by xesscorp** [comment]
Yeah, those static HTML files got lost when the XESS website got corrupted and I had to reload it from an older copy. I'll try to get them back on there, but the Jupyter notebook is the best way to view and interact with the examples.

**Comment by xesscorp** [comment]
OK, the static HTML files are restored.
