### ISSUE TITLE
Option for simulate functions to dump VCD

### ISSUE THREAD

**Issue by etch32** [xesscorp/pygmyhdl#3]
Hi,

I'm really enjoying this wrapper around myhdl as it seems more intuitive to me. I've been having some trouble with the Peeker.to_wavedrom function for long simulations (unable to get horizontal scrolling to work -- see related issue (https://github.com/xesscorp/myhdlpeek/issues/6 ). There are also times I may not want to run in a notebook.

As such I'd like to know if there is an option I can pass to the simulation wrapper functions, simulate(), random_sim(), exhaustive_sim(), clk_sim(), vector_sim() to enable dumping of VCD data? I tried a simplistic trace=True but got no output.

If there's not an existing option and it doesn't make sense to add, can you provide an example of how I'd accomplish this and still be able to use the above convenience functions?

Thank you

**Comment by xesscorp** [comment]
Below is an example of the [PWM module](https://github.com/xesscorp/pygmyhdl/blob/master/examples/3_pwm/pwm.ipynb) extracted to a Python script and modified to output VCD using the MyHDL `traceSignals` function:
```python
from pygmyhdl import *

@chunk
def pwm_simple(clk_i, pwm_o, threshold):
    cnt = Bus(3, name='cnt')

    @seq_logic(clk_i.posedge)
    def cntr_logic():
        cnt.next = cnt + 1

    @comb_logic
    def output_logic():
        pwm_o.next = cnt < threshold

initialize()
clk = Wire(name='clk')
pwm = Wire(name='pwm')
threshold = Bus(3, init_val=3)
traceSignals(pwm_simple, clk, pwm, threshold)
clk_sim(clk, num_cycles=24)
```
Then, run the script:
```bash
$ python pwm.py
```
Here's what the resulting `pwm_simple.vcd` file looks like in gtkwave:
![image](https://user-images.githubusercontent.com/845595/63227428-7607af80-c1b4-11e9-95e5-f075a5e48485.png)

**Comment by etch32** [comment]
OK, that was easy! Thank you for the example. I really appreciate your wrappers / enhancements to myhdl.

**Comment by xesscorp** [comment]
I'm glad they've been a help to you. Other than me, you might be the only other user.

Unfortunately, pygmydl depends on byteplay3 which hasn't been updated in four years and only supports Python 3.4 and 3.5. I'll have to find a more robust methodology if I want to continue development. Right now that's not a high priority, so hold onto your Python 3.5.

**Comment by etch32** [comment]
Yeah the byteplay3 thing is a bummer. I'd be happy if you found a work around as my other work is on 3.6 but understand it's not your highest priority. For now 3.5 will do.

I have to admit I was struggling with myhdl, especially with representing busses but your Bus and Wire classes really simplified it. Lots of other niceties too. You say in your docs that once I gain enough experience I may cast PygMyHDL aside but as long as there's no limitations to myhdl by using it (and there are none that I can see), I suspect I'll continue using it along with Peeker. Your great examples are what made coming up to speed easy. Once again thanks!

**Comment by xesscorp** [comment]
I'm glad it's working for you. If you develop anything open-source with it, let me know so I can see.

I guess this issue is resolved, so I'll close the thread.
